<!--EXTERNAL_PROPERTIES: GameVersion;-->
<Project Sdk="Bannerlord.BUTRModule.Sdk/1.1.0.129">

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    
    <BuildForWindows>true</BuildForWindows>
    <BuildForWindowsStore>true</BuildForWindowsStore>
    
    <!-- Module Id -->
    <ModuleId>Bannerlord.GABS</ModuleId>
    <!-- Module Name -->
    <ModuleName>AI Game Agent Server</ModuleName>
    <!-- Module Url -->
    <ModuleUrl>https://github.com/bennyz/Bannerlord.GABS</ModuleUrl>
    <!-- Module Version -->
    <Version>1.1.0</Version>
    <Platforms>x64</Platforms>
    <!-- Module manually override GameVersion -->
    <!-- <OverrideGameVersion>v1.0.0</OverrideGameVersion> -->

    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>BUTR</Authors>
  </PropertyGroup>

  <PropertyGroup>
    <HarmonyVersion>2.4.2</HarmonyVersion>
    <ButterLibVersion>2.11.0</ButterLibVersion>
    <MCMVersion>5.12.1</MCMVersion>

    <HarmonyExtensionsVersion>4.0.0.60</HarmonyExtensionsVersion>
    <BUTRModuleManagerVersion>6.0.247</BUTRModuleManagerVersion>
    <BUTRSharedVersion>3.0.0.142</BUTRSharedVersion>
    <BUTRModuleLoaderVersion>1.0.1.50</BUTRModuleLoaderVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Lib.GAB" Version="0.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="all" IncludeAssets="compile" />
    <ProjectReference Include="..\Bannerlord.GABS.Generators\Bannerlord.GABS.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

</Project>
